const SUPABASE_URL = window.BIYA_SUPABASE_URL || "https://pkjmkjyylgzjvhcreucc.supabase.co";
const SUPABASE_ANON_KEY = window.BIYA_SUPABASE_ANON_KEY || "sb_publishable_Tq4d0o3PIAd_zh11uJa2uQ_M_zPIYFX";
const configuredSupabaseClient = window.biyaSupabase || window.supabaseClient || null;
const supabaseClient = configuredSupabaseClient || ((SUPABASE_URL && SUPABASE_ANON_KEY && window.supabase) ? window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY) : null);
const settingsService = window.BiyaCostSettings;
let FOOD_COST_TARGET = settingsService?.DEFAULTS.food_cost_target || 35;
let PROFIT_TARGET = settingsService?.DEFAULTS.profit_target || 50;
let products = [];

function escapeHtml(value){ return String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c])); }
function safeText(value){ return String(value ?? "").trim(); }
function parseNumber(value){ if(typeof value === "number") return Number.isFinite(value) ? value : 0; let text = String(value ?? "").trim(); if(!text) return 0; text = text.replace(/rp/gi, "").replace(/\s/g, ""); if(text.includes(",") && text.includes(".")) text = text.replace(/\./g, "").replace(",", "."); else if(text.includes(",")) text = text.replace(",", "."); else text = text.replace(/\.(?=\d{3}(\D|$))/g, ""); const number = Number(text.replace(/[^0-9.-]/g, "")); return Number.isFinite(number) ? number : 0; }
function formatRupiah(value){ return "Rp " + Math.round(parseNumber(value)).toLocaleString("id-ID"); }
function formatPercent(value){ const number = Number(value); return Number.isFinite(number) ? number.toFixed(2) + "%" : "-"; }
function displayPercent(value, valid = true){ return valid && Number.isFinite(Number(value)) ? Number(value).toFixed(2) + "%" : "-"; }
function calcAverage(items, getter){ const values = items.map(getter).map(Number).filter(Number.isFinite); return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0; }
function isActive(product){ return String(product.status || "ACTIVE").toUpperCase() !== "INACTIVE"; }
function healthyFoodCostLimit(){ return settingsService ? settingsService.healthyFoodCostLimit(FOOD_COST_TARGET) : FOOD_COST_TARGET * 0.85; }
function statusClass(product){ if(!product.hasSelling || !product.hasRecipe) return "danger"; if(product.foodCostPct <= healthyFoodCostLimit()) return "ok"; if(product.foodCostPct <= FOOD_COST_TARGET) return "warn"; return "danger"; }
function statusText(product){ if(!product.hasSelling) return "Harga Jual Kosong"; if(!product.hasRecipe) return "HPP Belum Lengkap"; if(product.foodCostPct <= healthyFoodCostLimit()) return "Aman / Sehat"; if(product.foodCostPct <= FOOD_COST_TARGET) return "Perlu Dipantau"; return "Review Harga"; }
function normalizeMenuItem(row){ const qty = parseNumber(row.qty); const pricePerUnit = parseNumber(row.price_per_unit ?? row.pricePerUnit); const wastePercent = parseNumber(row.waste_percent ?? row.waste); const computedTotal = qty * pricePerUnit * (1 + wastePercent / 100); return { id:row.id, menuId:row.menu_id, ingredientType:row.ingredient_type || "raw_material", ingredientName:row.ingredient_name || row.nama_bahan || row.ingredient || "", qty, unit:row.unit || "", pricePerUnit, wastePercent, total:parseNumber(row.total) || computedTotal }; }
function normalizeProduct(row, items = []){ const normalizedItems = items.map(normalizeMenuItem); const recipeCost = normalizedItems.reduce((sum, item) => sum + item.total, 0); const sellingPrice = parseNumber(row.selling_price ?? row.sellingPrice ?? row.selling); const grossProfit = sellingPrice - recipeCost; const hasSelling = sellingPrice > 0; const hasRecipe = recipeCost > 0 && normalizedItems.length > 0; return { id:row.id, name:safeText(row.nama || row.name || row.menu || row.product || "Untitled"), category:safeText(row.category || row.cat || ""), subCategory:safeText(row.sub_category || row.subCategory || row.sub || ""), status:safeText(row.status || "ACTIVE"), sellingPrice, recipeCost, hpp:recipeCost, grossProfit, profitRp:grossProfit, grossMarginPct:hasSelling ? (grossProfit / sellingPrice) * 100 : 0, profitPct:hasSelling ? (grossProfit / sellingPrice) * 100 : 0, foodCostPct:hasSelling ? (recipeCost / sellingPrice) * 100 : 0, photoUrl:safeText(row.photo_url || row.photoUrl || row.photo || ""), description:safeText(row.description || ""), totalIngredients:normalizedItems.length, hasSelling, hasRecipe, items:normalizedItems }; }
function dashboardData(){ return products.filter(isActive); }

function showStatus(message = "", tone = "info"){ const box = document.getElementById("dashboardStatus"); if(!box) return; box.textContent = message; box.classList.toggle("hidden", !message); box.classList.toggle("loading", tone === "loading"); box.style.background = tone === "error" ? "rgba(255,77,79,.14)" : "rgba(16,43,99,.75)"; box.style.color = tone === "error" ? "#ffb4b4" : "rgba(215,227,255,.86)"; }
function emptyNotice(message){ return '<div class="notice">' + escapeHtml(message) + '</div>'; }

function buildAlerts(data = dashboardData()){
  const alerts = [];
  const validFood = data.filter(product => product.hasSelling && product.hasRecipe && product.foodCostPct > FOOD_COST_TARGET);
  const lowMargin = data.filter(product => product.hasSelling && product.grossMarginPct < PROFIT_TARGET);
  const noPhoto = data.filter(product => !product.photoUrl);
  const noRecipe = data.filter(product => !product.hasRecipe);
  const noSelling = data.filter(product => !product.hasSelling);
  const noCategory = data.filter(product => !product.category);
  const noSub = data.filter(product => !product.subCategory);
  if(validFood.length){ const product = [...validFood].sort((a,b) => b.foodCostPct - a.foodCostPct)[0]; alerts.push({ color:"red", icon:"FC", label:"Food Cost Warning", text:product.name + " berada di " + product.foodCostPct.toFixed(2) + "%, di atas target " + FOOD_COST_TARGET + "%.", action:"Cek Recipe", href:"menu.html" }); }
  if(lowMargin.length){ const product = [...lowMargin].sort((a,b) => a.grossMarginPct - b.grossMarginPct)[0]; alerts.push({ color:"red", icon:"%", label:"Review Harga", text:product.name + " memiliki margin " + product.grossMarginPct.toFixed(2) + "%.", action:"Review Harga", href:"producthpp.html" }); }
  if(noRecipe.length) alerts.push({ color:"yellow", icon:"H", label:"HPP Belum Lengkap", text:noRecipe.length + " produk belum memiliki recipe lengkap.", action:"Lengkapi HPP", href:"producthpp.html" });
  if(noSelling.length) alerts.push({ color:"red", icon:"Rp", label:"Harga Jual Kosong", text:noSelling.length + " produk belum memiliki selling price.", action:"Atur Harga", href:"menu.html" });
  if(noPhoto.length) alerts.push({ color:"yellow", icon:"+", label:"Missing Photo", text:noPhoto.length + " produk belum memiliki foto.", action:"Upload Foto", href:"menu.html" });
  if(noCategory.length) alerts.push({ color:"yellow", icon:"C", label:"Kategori Kosong", text:noCategory.length + " produk belum memiliki category.", action:"Lengkapi Data", href:"menu.html" });
  if(noSub.length) alerts.push({ color:"yellow", icon:"S", label:"Sub Category Kosong", text:noSub.length + " produk belum memiliki sub category.", action:"Lengkapi Data", href:"menu.html" });
  if(!alerts.length) alerts.push({ color:"green", icon:"OK", label:"Semua Terkendali", text:"Semua produk terlihat sehat dan siap dipantau.", action:"Lihat Menu", href:"menu.html" });
  return alerts;
}

function getHealthScore(avgMargin, avgFood, totalProduct, alertCount){ let score = 0; if(avgMargin >= PROFIT_TARGET) score += 2; else if(avgMargin >= PROFIT_TARGET * 0.8) score += 1; if(avgFood > 0 && avgFood <= FOOD_COST_TARGET) score += 2; else if(avgFood > 0 && avgFood <= FOOD_COST_TARGET * 1.15) score += 1; if(totalProduct >= 4) score += 1; if(alertCount <= 1) score += 1; else if(alertCount <= 3) score += 0.5; if(score >= 5) return { letter:"A", label:"Sangat Sehat" }; if(score >= 4) return { letter:"B", label:"Sehat" }; if(score >= 2.5) return { letter:"C", label:"Perlu Perhatian" }; return { letter:"D", label:"Bahaya" }; }
function topByProfit(data){ return [...data].filter(product => product.hasSelling).sort((a,b) => (b.grossProfit - a.grossProfit) || (b.grossMarginPct - a.grossMarginPct))[0]; }
function lowestByMargin(data){ return [...data].filter(product => product.hasSelling).sort((a,b) => (a.grossMarginPct - b.grossMarginPct) || (a.grossProfit - b.grossProfit))[0]; }

function renderSummary(){ const data = dashboardData(); const valid = data.filter(product => product.hasSelling); const avgMargin = calcAverage(valid, product => product.grossMarginPct); const avgFood = calcAverage(valid, product => product.foodCostPct); const revenue = data.reduce((sum, product) => sum + product.sellingPrice, 0); document.getElementById("dashTotalProduct").innerText = data.length; document.getElementById("dashAverageProfit").innerText = valid.length ? formatPercent(avgMargin) : "-"; document.getElementById("dashAverageFoodCost").innerText = valid.length ? formatPercent(avgFood) : "-"; document.getElementById("dashPotentialRevenue").innerText = formatRupiah(revenue); const alertCount = buildAlerts(data).filter(alert => alert.color !== "green").length; const score = getHealthScore(avgMargin, avgFood, data.length, alertCount); document.getElementById("healthScoreCard").innerHTML = '<div class="health-score-compact"><div class="score-circle">' + escapeHtml(score.letter) + '</div><div class="health-copy"><div class="health-label">' + escapeHtml(score.letter + " - " + score.label) + '</div><div class="muted">Kondisi bisnis berdasarkan target aktif</div></div></div><div class="health-metrics"><div class="health-metric"><span class="metric-label">Target FC</span><span class="metric-value">' + FOOD_COST_TARGET + '%</span></div><div class="health-metric"><span class="metric-label">Target Profit</span><span class="metric-value">' + PROFIT_TARGET + '%</span></div><div class="health-metric"><span class="metric-label">Produk</span><span class="metric-value">' + data.length + '</span></div><div class="health-metric"><span class="metric-label">Alert</span><span class="metric-value">' + alertCount + '</span></div></div><a class="health-cta" href="#quickAlertCard">Review Cost Control</a>'; }
function renderCompactProduct(product, tone = "best"){ if(!product) return emptyNotice("Belum ada data produk dari Supabase"); return '<div class="product-compact"><div class="product-compact-head"><div class="product-compact-thumb">' + (product.photoUrl ? '<img src="' + escapeHtml(product.photoUrl) + '" alt="' + escapeHtml(product.name) + '"/>' : '<div class="empty">No Photo</div>') + '</div><div class="product-compact-copy"><div class="product-name">' + escapeHtml(product.name) + '</div><div class="product-category-row"><span class="product-category-badge">' + escapeHtml(product.category || "Tanpa kategori") + '</span>' + (product.subCategory ? '<span class="product-category-badge secondary">' + escapeHtml(product.subCategory) + '</span>' : '') + '</div></div></div><div class="product-mini-stats"><div class="product-mini-stat ' + tone + '"><span class="metric-label">Profit</span><span class="metric-value">' + formatRupiah(product.grossProfit) + '</span></div><div class="product-mini-stat ' + tone + '"><span class="metric-label">Margin</span><span class="metric-value">' + displayPercent(product.grossMarginPct, product.hasSelling) + '</span></div></div></div>'; }
function renderBestWorst(){ const data = dashboardData(); document.getElementById("bestProductCard").innerHTML = renderCompactProduct(topByProfit(data), "best"); document.getElementById("worstProductCard").innerHTML = renderCompactProduct(lowestByMargin(data), "worst"); }
function renderRankings(){ const ranking = dashboardData().filter(product => product.hasSelling).sort((a,b) => (b.grossProfit - a.grossProfit) || (b.grossMarginPct - a.grossMarginPct)).slice(0,3); document.getElementById("rankingCard").innerHTML = ranking.length ? '<div class="ranking-list">' + ranking.map((product, index) => '<div class="ranking-item"><div class="ranking-position">' + (index + 1) + '</div><div class="ranking-copy"><div class="ranking-name">' + escapeHtml(product.name) + '</div><div class="ranking-category">' + escapeHtml(product.category || "Tanpa kategori") + '</div></div><div class="ranking-stats"><div class="ranking-profit">' + formatRupiah(product.grossProfit) + '</div><div class="ranking-margin">' + displayPercent(product.grossMarginPct, product.hasSelling) + '</div></div></div>').join("") + '</div>' : emptyNotice("Belum ada produk valid untuk ranking"); }
function renderSmartAlert(){ const alerts = buildAlerts(dashboardData()); document.getElementById("quickAlertCard").innerHTML = '<div class="alert-list">' + alerts.map(alert => '<div class="alert-item alert-' + alert.color + '"><span class="alert-icon">' + escapeHtml(alert.icon) + '</span><div class="alert-content"><div class="alert-label">' + escapeHtml(alert.label) + '</div><div class="alert-description">' + escapeHtml(alert.text) + '</div><a class="alert-action" href="' + escapeHtml(alert.href) + '">' + escapeHtml(alert.action) + '</a></div></div>').join("") + '</div>'; }
function renderCategoryPerformance(){ const groups = {}; dashboardData().forEach(product => { const key = product.category || "Uncategorized"; (groups[key] ||= []).push(product); }); const entries = Object.entries(groups).sort((a,b) => b[1].length - a[1].length); document.getElementById("categoryMeta").innerText = entries.length + " kategori"; document.getElementById("categoryPerformance").innerHTML = entries.map(([category, items]) => { const valid = items.filter(product => product.hasSelling); return '<div class="mini-box"><div class="mini-title">' + escapeHtml(category) + '</div><div class="mini-value">' + items.length + ' Product</div><div class="muted" style="margin-top:8px">Avg Profit ' + (valid.length ? formatPercent(calcAverage(valid, product => product.grossMarginPct)) : '-') + '</div><div class="muted">Avg Food Cost ' + (valid.length ? formatPercent(calcAverage(valid, product => product.foodCostPct)) : '-') + '</div></div>'; }).join("") || emptyNotice("Belum ada kategori dari Supabase"); }
function renderMissingData(){ const data = dashboardData(); const missing = []; const count = predicate => data.filter(predicate).length; const noPhoto = count(product => !product.photoUrl); const noSelling = count(product => !product.hasSelling); const noRecipe = count(product => !product.hasRecipe); const noCategory = count(product => !product.category); const noSub = count(product => !product.subCategory); const invalid = count(product => !Number.isFinite(product.sellingPrice) || !Number.isFinite(product.recipeCost)); if(noPhoto) missing.push({ color:"yellow", text:noPhoto + " produk belum memiliki foto" }); if(noSelling) missing.push({ color:"red", text:noSelling + " produk belum memiliki selling price" }); if(noRecipe) missing.push({ color:"red", text:noRecipe + " produk belum memiliki HPP/recipe lengkap" }); if(noCategory) missing.push({ color:"yellow", text:noCategory + " produk belum memiliki category" }); if(noSub) missing.push({ color:"yellow", text:noSub + " produk belum memiliki sub category" }); if(invalid) missing.push({ color:"red", text:invalid + " produk memiliki angka tidak valid" }); if(!missing.length) missing.push({ color:"green", text:"Semua data produk terlihat lengkap." }); document.getElementById("missingDataList").innerHTML = missing.map(item => '<div class="alert-item"><span class="alert-dot dot-' + item.color + '"></span><div>' + escapeHtml(item.text) + '</div></div>').join(""); }
function renderCompositionOptions(){ const select = document.getElementById("compositionSelect"); const data = dashboardData(); select.innerHTML = data.length ? data.map(product => '<option value="' + escapeHtml(product.id) + '">' + escapeHtml(product.name) + '</option>').join("") : '<option value="">Belum ada produk</option>'; }
function renderComposition(){ const id = document.getElementById("compositionSelect").value; const product = dashboardData().find(item => String(item.id) === String(id)) || dashboardData()[0]; const summary = document.getElementById("compositionSummary"); const bars = document.getElementById("compositionBars"); if(!product){ summary.innerText = ""; bars.innerHTML = emptyNotice("Belum ada data produk dari Supabase"); return; } if(!product.hasSelling || !product.hasRecipe){ summary.innerText = product.name; bars.innerHTML = emptyNotice("Komposisi biaya belum lengkap untuk produk ini."); return; } const items = [{ label:"Recipe / HPP", value:product.recipeCost, color:"#38bdf8" }, { label:"Gross Profit", value:Math.max(product.grossProfit, 0), color:"#34d399" }]; const total = product.sellingPrice || items.reduce((sum, item) => sum + item.value, 0) || 1; summary.innerText = product.name + " - HPP " + formatRupiah(product.recipeCost) + " - Selling " + formatRupiah(product.sellingPrice); bars.innerHTML = items.map(item => { const percentage = total ? (item.value / total) * 100 : 0; return '<div class="bar-item"><div class="bar-label">' + escapeHtml(item.label) + '</div><div class="bar-track"><div class="bar-fill" style="width:' + Math.max(percentage, 2) + '%;background:' + item.color + '"></div></div><div class="bar-value">' + formatPercent(percentage).replace(".00%", "%") + '</div></div>'; }).join(""); }
function populateCategoryFilter(){ const select = document.getElementById("filterHealthCategory"); const current = select.value; const categories = [...new Set(dashboardData().map(product => product.category).filter(Boolean))].sort((a,b) => a.localeCompare(b, "id")); select.innerHTML = '<option value="">All Category</option>' + categories.map(category => '<option value="' + escapeHtml(category) + '">' + escapeHtml(category) + '</option>').join(""); if(categories.includes(current)) select.value = current; }
function getFilteredProducts(){ const query = document.getElementById("searchHealth").value.trim().toLowerCase(); const category = document.getElementById("filterHealthCategory").value; return dashboardData().filter(product => { const haystack = [product.name, product.category, product.subCategory, product.status].join(" ").toLowerCase(); return (!query || haystack.includes(query)) && (!category || product.category === category); }); }
function renderHealthTable(){ const tbody = document.getElementById("healthTableBody"); const filtered = getFilteredProducts(); if(!dashboardData().length){ tbody.innerHTML = '<tr><td colspan="9" class="notice">Belum ada data produk. Tambahkan menu pertamamu untuk mulai menghitung HPP.</td></tr>'; renderBusinessInsight([]); return; } if(!filtered.length){ tbody.innerHTML = '<tr><td colspan="9" class="notice">Tidak ada produk yang cocok dengan pencarian atau filter.</td></tr>'; renderBusinessInsight(filtered); return; } tbody.innerHTML = filtered.map(product => { const health = statusClass(product); const foodWidth = product.hasSelling ? Math.min(Math.max(product.foodCostPct, 0), 100) : 0; const review = health === "danger" ? '<a class="review-price-btn" href="producthpp.html">Review Harga</a>' : ""; return '<tr><td>' + escapeHtml(product.name) + '</td><td>' + escapeHtml(product.category || "-") + '</td><td>' + escapeHtml(product.subCategory || "-") + '</td><td>' + formatRupiah(product.recipeCost) + '</td><td>' + (product.hasSelling ? formatRupiah(product.sellingPrice) : '-') + '</td><td>' + formatRupiah(product.grossProfit) + '</td><td>' + displayPercent(product.grossMarginPct, product.hasSelling) + '</td><td><div class="food-cost-cell"><div class="food-cost-value"><span>' + displayPercent(product.foodCostPct, product.hasSelling) + '</span><span class="muted">target ' + FOOD_COST_TARGET + '%</span></div><div class="food-cost-progress ' + health + '"><span style="width:' + foodWidth + '%"></span></div></div></td><td><span class="status ' + health + '">' + escapeHtml(statusText(product)) + '</span>' + review + '</td></tr>'; }).join(""); renderBusinessInsight(filtered); }
function toggleInsights(){ const list = document.getElementById("insightList"); if(!list) return; const expanded = list.classList.toggle("expanded"); const button = list.querySelector(".insight-toggle"); if(button){ button.textContent = expanded ? "Tampilkan lebih sedikit" : "Lihat semua insight"; button.setAttribute("aria-expanded", String(expanded)); } }
function renderBusinessInsight(list){ const data = list && list.length ? list : dashboardData(); const insights = []; const top = topByProfit(data); const low = lowestByMargin(data); const highFood = data.filter(product => product.hasSelling && product.hasRecipe && product.foodCostPct > FOOD_COST_TARGET); const noPhoto = data.filter(product => !product.photoUrl); const groups = {}; data.forEach(product => { const key = product.category || "Uncategorized"; (groups[key] ||= []).push(product); }); const bestCategory = Object.entries(groups).map(([category, items]) => ({ category, avgMargin:calcAverage(items.filter(product => product.hasSelling), product => product.grossMarginPct) })).sort((a,b) => b.avgMargin - a.avgMargin)[0]; if(top) insights.push('Produk terbaik saat ini adalah <b>' + escapeHtml(top.name) + '</b> dengan profit ' + displayPercent(top.grossMarginPct, top.hasSelling) + ' (' + formatRupiah(top.grossProfit) + ').'); if(low) insights.push('Produk yang perlu dicek adalah <b>' + escapeHtml(low.name) + '</b> karena margin ' + displayPercent(low.grossMarginPct, low.hasSelling) + '.'); if(highFood.length) insights.push('Ada <b>' + highFood.length + '</b> produk dengan food cost di atas target ' + FOOD_COST_TARGET + '%. Evaluasi recipe atau harga jual.'); if(noPhoto.length) insights.push('Ada <b>' + noPhoto.length + '</b> produk belum memiliki foto menu.'); if(bestCategory) insights.push('Kategori terbaik saat ini adalah <b>' + escapeHtml(bestCategory.category) + '</b> dengan average profit ' + formatPercent(bestCategory.avgMargin) + '.'); if(data.length) insights.push('Rata-rata profit seluruh produk adalah <b>' + formatPercent(calcAverage(data.filter(product => product.hasSelling), product => product.grossMarginPct)) + '</b>.'); const button = insights.length > 3 ? '<button class="insight-toggle" type="button" onclick="toggleInsights()" aria-expanded="false">Lihat semua insight</button>' : ""; document.getElementById("insightList").innerHTML = insights.length ? insights.map((insight, index) => '<div class="insight-item' + (index >= 3 ? ' is-extra' : '') + '">' + insight + '</div>').join("") + button : emptyNotice("Belum ada insight dari data Supabase"); }
function renderAll(){ renderSummary(); renderBestWorst(); renderRankings(); renderSmartAlert(); renderCategoryPerformance(); renderMissingData(); renderCompositionOptions(); renderComposition(); populateCategoryFilter(); renderHealthTable(); }

async function loadCostTargets(){ if(!settingsService){ const message = "Service Cost Settings tidak tersedia. Dashboard memakai target default 35% / 50%."; console.error("[Dashboard] Load cost_settings gagal", { message }); return message; } try{ const result = await settingsService.load(supabaseClient); FOOD_COST_TARGET = result.settings.food_cost_target; PROFIT_TARGET = result.settings.profit_target; return ""; }catch(error){ settingsService.logError("Dashboard gagal memuat cost_settings", error); return "Gagal memuat target Settings dari Supabase. Dashboard memakai target default 35% / 50%; cek console untuk detail."; } }
async function loadDashboardFromSupabase(){ if(!supabaseClient){ showStatus("Konfigurasi Supabase belum tersedia. Pastikan library Supabase dan anon key sudah termuat.", "error"); products = []; renderAll(); return; } showStatus("Memuat target Settings dan data dashboard dari Supabase...", "loading"); const targetWarning = await loadCostTargets(); try{ let menuResult = await supabaseClient.from("menus").select("*").order("created_at", { ascending:false }); if(menuResult.error && menuResult.error.code === "42703") menuResult = await supabaseClient.from("menus").select("*"); if(menuResult.error) throw menuResult.error; const menuRows = menuResult.data || []; const ids = menuRows.map(row => row.id).filter(Boolean); let itemRows = []; if(ids.length){ const itemResult = await supabaseClient.from("menu_items").select("*").in("menu_id", ids); if(itemResult.error) throw itemResult.error; itemRows = itemResult.data || []; } const itemMap = new Map(); itemRows.forEach(item => { const key = String(item.menu_id); if(!itemMap.has(key)) itemMap.set(key, []); itemMap.get(key).push(item); }); products = menuRows.map(row => normalizeProduct(row, itemMap.get(String(row.id)) || [])); const emptyMessage = products.length ? "" : "Belum ada data produk. Tambahkan menu terlebih dahulu."; showStatus([targetWarning, emptyMessage].filter(Boolean).join(" "), targetWarning ? "error" : "info"); renderAll(); }catch(error){ console.error("[Dashboard] Load Supabase gagal", { error, message:error?.message, details:error?.details, hint:error?.hint, code:error?.code }); products = []; showStatus("Gagal memuat data dashboard dari Supabase. Cek console untuk detail error.", "error"); renderAll(); } }

function setupMobileNavigation(){ const toggle = document.getElementById("menuToggle"); const sidebar = document.getElementById("biyaSidebar"); const overlay = document.getElementById("mobileOverlay"); if(!toggle || !sidebar || !overlay) return; const mobileQuery = window.matchMedia("(max-width: 980px)"); const closeButton = sidebar.querySelector(".sidebar-close"); const closeSidebar = () => { sidebar.classList.remove("open"); overlay.classList.remove("open"); document.body.classList.remove("biya-no-scroll"); toggle.setAttribute("aria-expanded", "false"); sidebar.setAttribute("aria-hidden", mobileQuery.matches ? "true" : "false"); overlay.setAttribute("aria-hidden", "true"); }; const openSidebar = () => { sidebar.classList.add("open"); overlay.classList.add("open"); document.body.classList.add("biya-no-scroll"); toggle.setAttribute("aria-expanded", "true"); sidebar.setAttribute("aria-hidden", "false"); overlay.setAttribute("aria-hidden", "false"); }; toggle.addEventListener("click", () => sidebar.classList.contains("open") ? closeSidebar() : openSidebar()); closeButton?.addEventListener("click", closeSidebar); overlay.addEventListener("click", closeSidebar); sidebar.addEventListener("click", event => { if(mobileQuery.matches && event.target.closest("a, .item, .btn")) closeSidebar(); }); document.addEventListener("keydown", event => { if(event.key === "Escape") closeSidebar(); }); const syncLayout = () => { if(mobileQuery.matches) sidebar.setAttribute("aria-hidden", sidebar.classList.contains("open") ? "false" : "true"); else { closeSidebar(); sidebar.setAttribute("aria-hidden", "false"); } }; mobileQuery.addEventListener ? mobileQuery.addEventListener("change", syncLayout) : mobileQuery.addListener(syncLayout); syncLayout(); }

document.addEventListener("DOMContentLoaded", () => { setupMobileNavigation(); loadDashboardFromSupabase(); });
